### PR TITLE
fixes: buttons upgraded

### PR DESCRIPTION
**Pull request by asutoshranjan**
Fixes issue #261 
- Replaced all raised buttons with elevated buttons
- Added few icons in buttons 
- minor fixes

### CODE REVIEW

**Review by abhibhaw — APPROVED** [review]

**Comment by abhibhaw** [comment]
@asutoshranjan Please check why the build is failing!!

**Review by SriramPatibanda — CHANGES_REQUESTED** [review]
Build is failing. Resolve that before we can merge this.

**Comment by abhibhaw** [comment]
@asutoshranjan  [Kotlin Migration](https://github.com/dscnitrourkela/project-avocado/actions/runs/3280194294/jobs/5400678576)

**Comment by asutoshranjan** [comment]
@abhibhaw I have upgraded the kotlin version and compile SDK version that's recommended, I am able to build the app on my mobile and emulator, exactly I don't know where the problem is 😥

**Review by SriramPatibanda — APPROVED** [review]

**Pull request merged**
