### PR TITLE
Add Adaptive & Legacy Icons Added.

### LINKED ISSUE #72: Create adaptive and legacy launcher icons
[Link for reference](https://developer.android.com/studio/write/image-asset-studio#create-adaptive)

### PR DESCRIPTION
**Pull request by abhibhaw**
Background -> #FFFFFF
Foreground -> 66% of ICS_logo.png
Closes #72

### CODE REVIEW

**Comment by DesignrKnight** [comment]
Can you send a screenshot of how the logo looks

**Comment by abhibhaw** [comment]
SS-1
ic_launcher-playstore
@DesignrKnight

**Review by DesignrKnight — APPROVED** [review]

**Comment by DesignrKnight** [comment]
@Thesmader approve when free
and when merging, add @ImgBotApp as a tool for contributors

**Review by Thesmader — APPROVED** [review]

**Comment by DesignrKnight** [comment]
### Hacktoberfest Thank You from NIT Rourkela community
It was a super fun experience in Hacktoberfest with you. We hope you also had fun and amazing learning. We look forward to you in our upcoming sessions and events as part of the community. 
You can join our Slack community at http://bit.ly/NITRDevs

**As a token of our gratitude, we have set up digital badges of recognition for our contributors from Hacktoberfest. 
Do claim yours at https://live.dscnitrourkela.org/**

Thanks and Cheers!
Stay Safe

**Pull request merged**
