### PR TITLE
Modified Timetable to automatically display accurate time table for the current Semester

### PR DESCRIPTION
**Pull request by pratik0197**
The timetable has been modified to automatically display the accurate one depending upon the current semester. 

Changes made : 

- Check if the current Semester is Autumn Semester.
- If it is Spring semester, internally change the section to the appropriate section(A changes to E,P1 changes to P6)
- Change the course Name of Maths and Physics-I if it is the Spring Semester.

### CODE REVIEW

**Comment by DesignrKnight** [comment]
Can you attach an APK?

**Review by SriramPatibanda — APPROVED** [review]
I've tested it. It works well! Great @pratik0197

**Review by SriramPatibanda — APPROVED** [review]

**Review by nayakastha — APPROVED** [review]
The changes are perfectly fine. Hey! @pratik0197, did you face any sort of issues while debugging? If there's no issue, it looks good for merging.

**Comment by pratik0197** [comment]
> Can you attach an APK?

@DesignrKnight this is the link to the google drive folder https://drive.google.com/file/d/1Z04r3Iw2Muf2ktPhBkobRtwdwJdnq5C2/view?usp=sharing

**Comment by pratik0197** [comment]
> The changes are perfectly fine. Hey! @pratik0197, did you face any sort of issues while debugging? If there's no issue, it looks good for merging.

No. didn't face any

**Pull request merged**
