### PR TITLE
Route refactor

### PR DESCRIPTION
**Pull request by SriramPatibanda**
Created a separate class to manage everything related to routes. Now, you can just tap into a specific route by using Routes.{nameOfTheRoute}.

### CODE REVIEW

**Review by DesignrKnight — APPROVED** [review]

**Comment by DesignrKnight** [comment]
@nayakastha 
This PR will be merged soon. Once done, use this route class for the new route you are adding in #109

**Review by Thesmader — CHANGES_REQUESTED** [review]
@SriramPatibanda you added the file .flutter-plugins-dependencies to .gitignore. Please unstage the file in git and push the new commit to the same branch. The PR can be merged after that.

**Comment by DesignrKnight** [comment]
@SriramPatibanda can you fetch upstream, resolve merge conflict
add flutter-plugin-dependencies to gitignore unstage flutter-plugin-dependencies and update PR?

**Comment by SriramPatibanda** [comment]
> @SriramPatibanda can you fetch upstream, resolve merge conflict
> add flutter-plugin-dependencies to gitignore unstage flutter-plugin-dependencies and update PR?

@DesignrKnight I've resolved the merge conflicts, please review them and merge.

**Comment by DesignrKnight** [comment]
@nayakastha merged!
Can you fetch and update PR

**Comment by DesignrKnight** [comment]
### Hacktoberfest Thank You from NIT Rourkela community
It was a super fun experience in Hacktoberfest with you. We hope you also had fun and amazing learning. We look forward to you in our upcoming sessions and events as part of the community. 
You can join our Slack community at http://bit.ly/NITRDevs

**As a token of our gratitude, we have set up digital badges of recognition for our contributors from Hacktoberfest. 
Do claim yours at https://live.dscnitrourkela.org/**

Thanks and Cheers!
Stay Safe

**Pull request merged**
