### PR TITLE
Upgrading android embedding

### PR DESCRIPTION
**Pull request by SriramPatibanda**
Made changes to the mentioned files according to the [official guide](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects). Since MainActivity.kt had to be changed, I converted the MainActivity.java file to kotlin. The Application.java also required changes. The new android embedding doesn't require overriding onCreate and registering the plugin as the flutter manages that automatically now. In the same file, instead of using with PluginRegistry, I registered it with the flutter engine.

### CODE REVIEW

**Comment by DesignrKnight** [comment]
@Thesmader 
Approve, Squash and Merge

Thanks @SriramPatibanda

**Comment by Thesmader** [comment]
@Chinmay-KB mind taking a look at the native kotlin code?

**Review by Thesmader — CHANGES_REQUESTED** [review]
@SriramPatibanda there are some files that do not end with a new line. Please check the Files Changed tab and add a new line at the end of these files.

**Comment by SriramPatibanda** [comment]
> @SriramPatibanda there are some files that do not end with a new line. Please check the Files Changed tab and add a new line at the end of these files.

Done. Added a missing new line at the end of files.

**Review by Chinmay-KB — APPROVED** [review]
Clear from here!

**Review by Thesmader — APPROVED** [review]

**Pull request merged**
