### PR TITLE
Fix Landscape rotation

### LINKED ISSUE #77: Fix Landscape rotation
image

### PR DESCRIPTION
**Pull request by abhibhaw**
Changed => (screenWidth * 0.010). Please verify twice before merging....

Because I am not confident :(

Before:
ss_before

After:
The app is fixed to portrait orientation.
ss-after

### CODE REVIEW

**Comment by DesignrKnight** [comment]
Can you please explain why woukd screen width fix tbe issue?

**Comment by DesignrKnight** [comment]
To fix that we need to change Android Manifest, isn't it @Thesmader

**Comment by abhibhaw** [comment]
I didn't change the screen width... I just adjusted the top padding.... and it's worked for me. [CHECK SCREENSHOT](https://drive.google.com/drive/folders/1uI1GpjyHnTiXPXBcYVMJpJWq_iiXOreX?usp=sharing)

**Comment by DesignrKnight** [comment]
Can you just disable landscape orientation and fix only portrait?
Else for every page we'll need a landscape design

For now, just have portrait as only orientation

**Comment by Thesmader** [comment]
@abhibhaw Can you include the before and after screenshots of the changes you made in your [PR description](https://github.com/dscnitrourkela/project-avocado/pull/85#issue-483654235)? Please try to follow this whenever you make any UI changes 😄

**Comment by abhibhaw** [comment]
Okay @Thesmader Bhaiya, I will follow the same 😄

**Comment by abhibhaw** [comment]
@DesignrKnight Bhaiya, Done as instructed. 👍 [Check Screen Shots](https://drive.google.com/drive/folders/1OvJmRRK39PprYNpKTKSQsQF42Turk9Vz?usp=sharing)

**Comment by DesignrKnight** [comment]
@Thesmader 
Check and approve

**Review by Thesmader — APPROVED** [review]
The changes are good to go!

**Review by DesignrKnight — APPROVED** [review]

**Comment by DesignrKnight** [comment]
@all-contributors add @abhibhaw for Code, Accessibility

**Comment by DesignrKnight** [comment]
@all-contributors add @abhibhaw for Code, Accessibility

**Pull request merged**
