### PR TITLE
blank Screen bug-fix

### PR DESCRIPTION
**Pull request by SriramPatibanda**
Resolved the issue by making minor changes to the widget tree. Ready to be merged.

### CODE REVIEW

**Comment by Thesmader** [comment]
Hey @SriramPatibanda, can you explain the changes you made to fix the black screen issue while exiting the app? Maybe you could tell about your approach to fixing the bug and any other specifics of the changes you made.

**Comment by SriramPatibanda** [comment]
> Hey @SriramPatibanda, can you explain the changes you made to fix the black screen issue while exiting the app? Maybe you could tell about your approach to fixing the bug and any other specifics of the changes you made.

Initially, I thought the issue could be resolved using double tap to exit screen functionality and implemented it, but it didn't work. 
So, I went through @Chinmay-KB 's old PR and implemented the same. So, I wrapped future builder under a Scaffold. and instead of calling checkLogin in initstate, I used a future builder.

**Comment by DesignrKnight** [comment]
If you are referencing @Chinmay-KB 's old PR, can you rebase that and do?
That way, both of your's commit gets merged

**Comment by Thesmader** [comment]
If @SriramPatibanda's PR fixes the bug independently, I don't think there is a need to do any other rebase/merge. We can use this PR and simply close #53

**Comment by Chinmay-KB** [comment]
Rebase is not required, this commit does everything intended in the previous pr

**Review by Chinmay-KB — APPROVED** [review]

**Comment by Chinmay-KB** [comment]
@Thesmader @DesignrKnight review

**Review by DesignrKnight — APPROVED** [review]
Seems good

**Comment by DesignrKnight** [comment]
@all-contributors add @SriramPatibanda for Code

**Pull request merged**
