### PR TITLE
Attendance Tracker

### PR DESCRIPTION
**Pull request by nayakastha**
WhatsApp Image 2020-09-26 at 18 23 04
Initial Layout. Open for Changes. Also there was subtle request to add notifications for exceeding absents. work left on that

### CODE REVIEW

**Comment by DesignrKnight** [comment]
UI looks neat. Is data stored locally or Firebase?

**Comment by nayakastha** [comment]
The data is stored locally. This will have too many reads and writes so didn't want to involve Firebase.

**Comment by DesignrKnight** [comment]
Ideally, it should be stored online as user may re-install the app and entire data will be gone.

The free tier limit seems good enough for me.
https://firebase.google.com/docs/firestore/quotas#free-quota

**Comment by nayakastha** [comment]
I will make it to online Strorage.

**Comment by DesignrKnight** [comment]
Umm....Why close?
Restarting the work?

**Pull request closed without merging**
