### PR TITLE
fix: Fixes workflow pr build comment issue

### PR DESCRIPTION
**Pull request by abhibhaw**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Description
Please describe your pull request.

❤️Thank you!

### Post merge checklist
- [ ] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

### CODE REVIEW

**Comment by abhibhaw** [comment]
@DesignrKnight Wasn't it supposed to comment the status badge 🤣

**Comment by abhibhaw** [comment]
Probably it will comment once merged as it may not be able to action token from an external branch.

**Comment by DesignrKnight** [comment]
Was it working earlier before your change?

**Comment by abhibhaw** [comment]
> Was it working earlier before your change?

[logs](https://github.com/dscnitrourkela/project-avocado/actions/workflows/greetings.yml) last worked 7 months ago

**Review by nayakastha — APPROVED** [review]

**Review by SriramPatibanda — APPROVED** [review]

**Comment by DesignrKnight** [comment]
Created a test-actions branch and changes the base of PR. Merge and test it against that

**Pull request merged**
