### PR TITLE
Adaptive and Legacy Launcher Icons Added.

### LINKED ISSUE #72: Create adaptive and legacy launcher icons
[Link for reference](https://developer.android.com/studio/write/image-asset-studio#create-adaptive)

### PR DESCRIPTION
**Pull request by abhibhaw**
Closes #72

Followed the Reference Linked: Foreground Asset -> Image (SCP LOGO.png)
Background Asset -> Color(#FFFFFF)

### CODE REVIEW

**Comment by DesignrKnight** [comment]
Hey, I assume you used the black colored logo. Can we have that changed? I can send the right color here

**Review by DesignrKnight — CHANGES_REQUESTED** [review]
I think the present app logo colour is bluish, let us stick to that

**Comment by DesignrKnight** [comment]
Updated new logo in repo. Kindly see

**Comment by abhibhaw** [comment]
@DesignrKnight Updated with the latest logo -> ICS_logo.png

**Comment by DesignrKnight** [comment]
Looks good

**Review by DesignrKnight — APPROVED** [review]

**Comment by DesignrKnight** [comment]
@Thesmader , Approve and merge

**Comment by abhibhaw** [comment]
Will Send Again!!
Hacktober Party ;)

**Comment by DesignrKnight** [comment]
Fixed in #106

**Pull request closed without merging**
