### PR TITLE
added network connectivity status #70

### PR DESCRIPTION
**Pull request by rajnis09**
#70 Completed the **"Have the app show the user the network connectivity status"**  issue

@DesignrKnight have a check when you get time.

### CODE REVIEW

**Comment by DesignrKnight** [comment]
Can we have some photos/video showing the change?

**Comment by DesignrKnight** [comment]
@Chinmay-KB @Thesmader 
Review, when possible

**Comment by rajnis09** [comment]
I am adding a short video in a while

**Comment by rajnis09** [comment]
ezgif com-gif-maker (1)



Have look and please review it again. @DesignrKnight 

Thanks

**Review by Chinmay-KB — APPROVED** [review]

**Comment by DesignrKnight** [comment]
> ezgif com-gif-maker (1)
> 
> Have look and please review it again. @DesignrKnight
> 
> Thanks

This looks amazing. Really good

**Comment by rajnis09** [comment]
@DesignrKnight will you approve these changes so that merging can be done 

> > ezgif com-gif-maker (1)
> > Have look and please review it again. @DesignrKnight
> > Thanks
> 
> This looks amazing. Really good

@DesignrKnight will you approve these changes so that it can be merged

**Review by DesignrKnight — APPROVED** [review]

**Comment by DesignrKnight** [comment]
Thanks so much for your PR. We are super happy

**Comment by rajnis09** [comment]
> Thanks so much for your PR. We are super happy

> Thanks to your team too.

**Comment by DesignrKnight** [comment]
@all-contributors add @rajnis09 for Code

**Comment by DesignrKnight** [comment]
### Hacktoberfest Thank You from NIT Rourkela community
It was a super fun experience in Hacktoberfest with you. We hope you also had fun and amazing learning. We look forward to you in our upcoming sessions and events as part of the community. 
You can join our Slack community at http://bit.ly/NITRDevs

**As a token of our gratitude, we have set up digital badges of recognition for our contributors from Hacktoberfest. 
Do claim yours at https://live.dscnitrourkela.org/**

Thanks and Cheers!
Stay Safe

**Pull request merged**
