### PR TITLE
Update To Use GraphQL For App Data Partially

### LINKED ISSUE #154: Add Co-ordinator and Prefect names in the Mentor detail card

### PR DESCRIPTION
**Pull request by nayakastha**
Merging this closes #154 and #136

### CODE REVIEW

**Comment by Chinmay-KB** [comment]
The graphql url is exposed. Is it fine or should we remedy this?
We can use remoteconfig to pass the URL, if that helps

@DesignrKnight @Thesmader

**Comment by Thesmader** [comment]
There's a better [solution](https://pub.dev/packages/envify)

**Comment by DesignrKnight** [comment]
If you are using .env, tell me
I need to add that to CI-CD
We will have auth for GraphQL soon, but yeah, APIs can always be missed if someone wants to.

**Comment by DesignrKnight** [comment]
image
Is this false trigger or legit?
Check the GitGuardian CI above

**Review by abhibhaw — APPROVED** [review]

**Review by DesignrKnight — APPROVED** [review]

**Pull request merged**
