### PR TITLE
De-cluttered main.dart

### LINKED ISSUE #105: Make main.dart de-cluttered
Present main.dart file is too complex. Having the functionality separated would make the code clean and easy to manage

### PR DESCRIPTION
**Pull request by priyanshu0405**
Closes #105 

Made 2 new files `HomePage.dart` and `myApp.dart` in `scp/lib` to de-clutter `main.dart`

### CODE REVIEW

**Comment by Chinmay-KB** [comment]
There was an issue we had recently solved #30 , can you check if your code breaks it or is it fine?

**Comment by priyanshu0405** [comment]
The app is not running it shows -
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it.

I have just moved the 2 classes MyApp and HomePage to 2 seperate dart files, it should function as earlier.

**Comment by DesignrKnight** [comment]
@priyanshu0405 
Send over your Firebase email ID. That will get you access to google-services.json

**Comment by priyanshu0405** [comment]
priyanshu0405jain@gmail.com

**Comment by DesignrKnight** [comment]
Have added to our Firebase project, kindly download JSON file from there and do. If you still have issues, reach to us

**Comment by priyanshu0405** [comment]
Hey @DesignrKnight, the app asks me for a phone number to verify.

**Comment by DesignrKnight** [comment]
You can use any phone number to login

**Comment by priyanshu0405** [comment]
It shows a snackbar with messege "booooo!" when I use my phone number.

**Comment by DesignrKnight** [comment]
What? Really?
That sounds new ☹️

**Comment by DesignrKnight** [comment]
Can you send a screenshot

**Comment by DesignrKnight** [comment]
image

Use one of these if yours does not work

**Comment by priyanshu0405** [comment]
@DesignrKnight, I have tried it with the above mentioned number and the app works fine. Issue #30 also works perfectly fine.

**Comment by DesignrKnight** [comment]
Can you just fix the conflict with merge
Will merge after review
Seems perfect

**Comment by DesignrKnight** [comment]
@Chinmay-KB @Thesmader 

Check and approve

**Review by Chinmay-KB — APPROVED** [review]
Good to go

**Review by DesignrKnight — APPROVED** [review]

**Comment by DesignrKnight** [comment]
@all-contributors add @priyanshu0405 for Code

**Comment by DesignrKnight** [comment]
### Hacktoberfest Thank You from NIT Rourkela community
It was a super fun experience in Hacktoberfest with you. We hope you also had fun and amazing learning. We look forward to you in our upcoming sessions and events as part of the community. 
You can join our Slack community at http://bit.ly/NITRDevs

**As a token of our gratitude, we have set up digital badges of recognition for our contributors from Hacktoberfest. 
Do claim yours at https://live.dscnitrourkela.org/**

Thanks and Cheers!
Stay Safe

**Pull request merged**
